### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by BlackHT** [cpanato/mattermost-plugin-broadcast-message#1]
HI
i use this plugin on https protocol mattermost server
but noting action and show log message

{"level":"debug","ts":1627980566.7028348,"caller":"mlog/log.go:211","msg":"Action integration error.","path":"/api/v4/actions/dialogs/submit","request_id":"q9cxkge7iinspg7yj9kkhayfgr","ip_addr":"(my-ip)","user_id":"rmxa8194epb37mtcox7mj68u7a","method":"POST","err_where":"DoActionRequest","http_code":400,"err_details":"status=400"}

{"level":"debug","ts":1627980566.7029321,"caller":"web/handlers.go:105","msg":"Received HTTP request","method":"POST","url":"/api/v4/actions/dialogs/submit","request_id":"q9cxkge7iinspg7yj9kkhayfgr","host":"(my-dns)","scheme":"","status_code":"400"}

can't using https protocol server?

**Comment by cpanato** [comment]
hello @BlackHT I will take a look at this and if this is an issue I will fix it

**Comment by BlackHT** [comment]
thanks!

**Comment by cpanato** [comment]
@BlackHT this should fix your issue, there is a new release: https://github.com/cpanato/mattermost-plugin-broadcast-message/releases/tag/v0.1.1

**Comment by BlackHT** [comment]
> @BlackHT this should fix your issue, there is a new release: https://github.com/cpanato/mattermost-plugin-broadcast-message/releases/tag/v0.1.1

hi.. i testing my server new plugin
but show error message and not doing
both https and http server show error message 

{"level":"error","ts":1628648354.410963,"caller":"mlog/log.go:232","msg":"RPC call to OnActivate plugin failed.","plugin_id":"com.cpanato.broadcast","error":"EOF"}
{"level":"debug","ts":1628648354.4128878,"caller":"jobs/workers.go:189","msg":"Workers received config change."}
{"level":"debug","ts":1628648354.4129467,"caller":"plugin/environment.go:508","msg":"Enabling plugin health check job","interval_s":30}
{"level":"debug","ts":1628648354.4129872,"caller":"mlog/log.go:211","msg":"Not auto installing/upgrade because plugin was disabled","plugin_id":"com.mattermost.plugin-incident-management","version":"1.5.2"}
{"level":"debug","ts":1628648354.4152637,"caller":"plugin/health_check.go:31","msg":"Plugin health check job starting."}
{"level":"debug","ts":1628648354.6460185,"caller":"plugin/hclog_adapter.go:54","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.64613,"caller":"plugin/hclog_adapter.go:54","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x3a0 pc=0xc40267]","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6461678,"caller":"plugin/hclog_adapter.go:54","msg":"","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6461868,"caller":"plugin/hclog_adapter.go:54","msg":"goroutine 35 [running]:","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6462057,"caller":"plugin/hclog_adapter.go:54","msg":"main.(*Plugin).OnConfigurationChange(0xc00006e540, 0xddc400, 0xc00006e540)","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.646235,"caller":"plugin/hclog_adapter.go:54","msg":"\t/Users/cpanato/code/src/github.com/cpanato/mattermost-plugin-broadcast-message/server/configuration.go:77 +0x47","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6462557,"caller":"plugin/hclog_adapter.go:54","msg":"github.com/mattermost/mattermost-server/v5/plugin.(*hooksRPCServer).OnConfigurationChange(0xc0003c0220, 0x14da040, 0xc000030dc0, 0x0, 0x0)","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6462767,"caller":"plugin/hclog_adapter.go:54","msg":"\t/Users/cpanato/code/pkg/mod/github.com/mattermost/mattermost-server/v5@v5.37.0/plugin/client_rpc_generated.go:77 +0x66","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6463046,"caller":"plugin/hclog_adapter.go:54","msg":"reflect.Value.call(0xc0003beba0, 0xc0000b42b8, 0x13, 0xe35cb1, 0x4, 0xc000084f08, 0x3, 0x3, 0x0, 0x0, ...)","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6463244,"caller":"plugin/hclog_adapter.go:54","msg":"\t/usr/local/Cellar/go/1.16.6/libexec/src/reflect/value.go:476 +0x8e7","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6463437,"caller":"plugin/hclog_adapter.go:54","msg":"reflect.Value.Call(0xc0003beba0, 0xc0000b42b8, 0x13, 0xc0003c8f08, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6463895,"caller":"plugin/hclog_adapter.go:54","msg":"\t/usr/local/Cellar/go/1.16.6/libexec/src/reflect/value.go:337 +0xb9","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6464117,"caller":"plugin/hclog_adapter.go:54","msg":"net/rpc.(*service).call(0xc0003a8000, 0xc0000801e0, 0xc0002b4080, 0xc0002b4090, 0xc0000fa600, 0xc0003c02a0, 0xc9f5a0, 0x14da040, 0x16, 0xc9f5e0, ...)","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6464324,"caller":"plugin/hclog_adapter.go:54","msg":"\t/usr/local/Cellar/go/1.16.6/libexec/src/net/rpc/server.go:377 +0x189","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6464608,"caller":"plugin/hclog_adapter.go:54","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.cpanato.broadcast"}
{"level":"debug","ts":1628648354.6464891,"caller":"plugin/hclog_adapter.go:54","msg":"\t/usr/local/Cellar/go/1.16.6/libexec/src/net/rpc/server.go:474 +0x44d","plugin_id":"com.cpanato.broadcast"}
{"level":"error","ts":1628648354.6571589,"caller":"mlog/log.go:232","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"com.cpanato.broadcast","error":"unexpected EOF"}
{"level":"debug","ts":1628648354.6572719,"caller":"jobs/schedulers.go:214","msg":"Schedulers received config change."}
{"level":"debug","ts":1628648354.6620083,"caller":"plugin/hclog_adapter.go:52","msg":"plugin process exited","plugin_id":"com.cpanato.broadcast","wrapped_extras":"pathplugins/com.cpanato.broadcast/server/dist/plugin-linux-amd64pid32525errorexit status 2"}
{"level":"debug","ts":1628648354.6838472,"caller":"web/handlers.go:105","msg":"Received HTTP request","method":"POST","url":"/api/v4/plugins/com.cpanato.broadcast/enable","request_id":"17786adry78a9donizmn9wy9ya","host":"(my-domain-address)","scheme":"","status_code":"200"}


thanks..

**Comment by cpanato** [comment]
@BlackHT with version of mattermost are you using? and did you configure the token?

**Comment by BlackHT** [comment]
mattermost version is 5.34.0 and configure the token
upload plugin and not auto creating bot.. and not showing command

**Comment by cpanato** [comment]
@BlackHT tested here with 5.34 and 5.37 and both worked with localhost (HTTP) and with a HTTPS configured

did you configure the server to enable the bot creation? `Enable Bot Account Creation` and enable some configs in the `Integration Management`

**Comment by cpanato** [comment]
ok, tried in another server and saw one issue, checking

**Comment by cpanato** [comment]
@BlackHT i know why, because the last release I've update the dependencies to use mattermost v5.37.0 and your server is running v5.34.X and from 5.34 to 5.37 there are some changes that are not compatible.

Let me know if you can upgrade your server to 5.37 and then you can use this package otherwise we will need to build a custom one for 5.34.0

in fact is just change the dependencies to 5.34.0 run go mod tidy and build a new package

**Comment by BlackHT** [comment]
oh! thanks! i'll tring!

**Comment by BlackHT** [comment]
sorry it too late..
i updated server version and it working !!
thanks!!

**Comment by cpanato** [comment]
cool! nice to hear!
let me know what you think about this plugin and maybe features you would like to see
